name: CI/CD with ArgoCD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-k8s-deployment:${{ github.sha }} .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-k8s-deployment:${{ github.sha }}

    - name: Checkout manifests repository
      uses: actions/checkout@v2
      with:
        repository: fatmamrabet/repo-kubernetes-configs  # Remplace par le chemin de ton dépôt
        path: manifests
        token: ${{ secrets.PAT_GITHUB }}

    - name: Update Kubernetes manifests
      run: |
        sed -i 's#image: .*$#image: '"${{ secrets.DOCKER_USERNAME }}/springboot-k8s-deployment:${{ github.sha }}"'#g' manifests/deployment-springboot.yaml

    - name: Commit and push changes
      run: |
        cd manifests
        git config --global user.email "fatma.mrabet@esprit.tn"  # Remplace par ton email
        git config --global user.name "fatmamrabet"  # Remplace par ton nom
        git add .
        git commit -m "Update image to ${{ github.sha }}"
        git push https://fatmamrabet:${{ secrets.PAT_GITHUB }}@github.com/fatmamrabet/repo-kubernetes-configs.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
