name: CI/CD Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package -DskipTests
    
    - name: Run tests
      run: mvn test

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-k8s-deployment:1.0 .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-k8s-deployment:1.0

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/spring-deployment spring-container=${{ secrets.DOCKER_USERNAME }}/springboot-k8s-deployment:1.0 --record
        kubectl rollout status deployment/spring-deployment
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}